version: '3.8'

services:
  # Portfolio development server
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.arm64
    container_name: portfolio-dev
    ports:
      - '3001:3001'
      - '9229:9229' # Node.js debug port
    volumes:
      # Mount source code for hot reloading
      - ./WIP/v1:/app/WIP/v1
      - ./assets:/app/assets
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      # Preserve node_modules in container
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - CHOKIDAR_USEPOLLING=true # For file watching in containers
    restart: unless-stopped
    networks:
      - portfolio-network

  # Optional: Add a reverse proxy for production testing
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./WIP/v1:/usr/share/nginx/html:ro
    depends_on:
      - portfolio-dev
    networks:
      - portfolio-network
    profiles:
      - production-test

networks:
  portfolio-network:
    driver: bridge

volumes:
  node_modules:
