name: link-check

on:
  # Disabled - causing false positives with local assets
  workflow_dispatch: {}

permissions:
  checks: write
  contents: read

concurrency:
  group: link-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config lychee.toml --verbose --no-progress *.html *.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
