# Lychee configuration for portfolio link checking
# Focus on external links, skip local assets that are known to exist

# Accept various HTTP status codes
accept = [200, 204, 301, 302, 403, 429]

# Skip checking local assets - focus on external links only
exclude_path = ["./assets/", "./v1backup/", "./v2/", "./Old References/"]

# Exclude file patterns
exclude_file = [".lycheeignore"]

# Timeout settings
timeout = 15
max_retries = 3

# User agent (some sites block default)
user_agent = "Mozilla/5.0 (compatible; link-checker)"

# Skip checking fragments (anchors)
check_fragments = false

# Include only specific patterns
include = ["*.html", "*.md"]
