name: Link check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main] # run on PRs into main
  schedule:
    - cron: "17 3 * * 1"
  workflow_dispatch: {}
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --max-retries 3 --retry-wait-time 2 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
