name: link-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  checks: write
  contents: read

concurrency:
  group: link-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  link-check:
    name: link-check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --max-retries 3 --retry-wait-time 2 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
